/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.tema17.practica.mascotas.interfaces;

import es.medac.tema17.practica.mascotas.controller.ConsultasMascotasApp;
import es.medac.tema17.practica.mascotas.model.clientes;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Andrés
 */
public class GestionDeDatos extends javax.swing.JFrame {

    /**
     * Creates new form GestionDeDatos
     */
    public GestionDeDatos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonInsertarPacientes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldCuentaBanco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInforme = new javax.swing.JTextArea();
        jButtonInsertarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonInsertarPesos = new javax.swing.JButton();
        jButtonInsertarVacunas = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("GESTIÓN DE DATOS");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 520, 100));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 110, 30));

        jButtonVolver.setBackground(new java.awt.Color(204, 204, 255));
        jButtonVolver.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonVolver.setText("VOLVER");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 110, 30));

        jButtonInsertarPacientes.setBackground(new java.awt.Color(204, 204, 255));
        jButtonInsertarPacientes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonInsertarPacientes.setText("INSERTAR PACIENTES");
        getContentPane().add(jButtonInsertarPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Insercción de Clientes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Teléfono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jTextFieldIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("IdCliente: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nombre: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        getContentPane().add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 70, -1));
        getContentPane().add(jTextFieldCuentaBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 70, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Primer Apellido: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Cuenta Banco:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jTextAreaInforme.setColumns(20);
        jTextAreaInforme.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInforme);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 290, -1));

        jButtonInsertarCliente.setText("INSERTAR");
        jButtonInsertarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsertarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 400, 300));

        jButtonInsertarPesos.setBackground(new java.awt.Color(204, 204, 255));
        jButtonInsertarPesos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonInsertarPesos.setText("INSERTAR PESOS");
        getContentPane().add(jButtonInsertarPesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 180, 30));

        jButtonInsertarVacunas.setBackground(new java.awt.Color(204, 204, 255));
        jButtonInsertarVacunas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonInsertarVacunas.setText("INSERTAR VACUNAS");
        getContentPane().add(jButtonInsertarVacunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 180, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/medac/tema17/practica/mascotas/interfaces/imagenes/imagen.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel1");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 780, 516));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        Interfaz1 gestiondedatos = new Interfaz1();
        gestiondedatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdClienteActionPerformed

    private void jButtonInsertarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarClienteActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps = null;
        boolean InserccionExitosa = false;
        
        
        
        int IdCliente = Integer.parseInt(jTextFieldIdCliente.getText());
        String Nombre = jTextFieldNombre.getText();
        String Apellido = jTextFieldApellido.getText();
        int CuentaBanco = Integer.parseInt(jTextFieldCuentaBanco.getText());
        int Telefono = Integer.parseInt(jTextFieldTelefono.getText());
        
        
        ConsultasMascotasApp con1 = new ConsultasMascotasApp();
        
        
        clientes clientes1 = new clientes(IdCliente, Apellido, 
                CuentaBanco, Telefono);
        String informe = clientes1.imprimir();
        jTextAreaInforme.setText(informe);
        try {
            con1.insertarClientes(IdCliente, Apellido, CuentaBanco, Telefono);
            con1.insertarPersonas(IdCliente, Nombre, Apellido, Telefono);
            int filasActualizadas = ps.executeUpdate();
             
             if (filasActualizadas > 0){
                 jTextAreaInforme.setText("Ha insertado los datos correctamente. "+informe);
                 InserccionExitosa= true;
             } else {
                 jTextAreaInforme.setText("No se encontró al cliente con id: "+IdCliente);
             }
        } catch (SQLException ex) {
            Logger.getLogger(GestionDeDatos.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        
    }//GEN-LAST:event_jButtonInsertarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDeDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertarCliente;
    private javax.swing.JButton jButtonInsertarPacientes;
    private javax.swing.JButton jButtonInsertarPesos;
    private javax.swing.JButton jButtonInsertarVacunas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInforme;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCuentaBanco;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
