/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.tema17.practica.mascotas.interfaces;

import es.medac.tema17.practica.mascotas.controller.ConsultasMascotasApp;
import es.medac.tema17.practica.mascotas.model.clientes;
import es.medac.tema17.practica.mascotas.model.pacientes;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Andrés
 */
public class InsertarYModificarPacientes extends javax.swing.JFrame {

    /**
     * Creates new form GestionDeDatos
     */
    public InsertarYModificarPacientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIdMascota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jTextFieldAliasMascota = new javax.swing.JTextField();
        jTextFieldEspecie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRaza = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInforme = new javax.swing.JTextArea();
        jButtonInsertarPaciente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldColorPelo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldFechaNacimiento = new javax.swing.JTextField();
        jTextFieldVacunaciones = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldIdPaciente2 = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldIdMascota1 = new javax.swing.JTextField();
        jTextFieldAliasMascota1 = new javax.swing.JTextField();
        jTextFieldEspecie1 = new javax.swing.JTextField();
        jTextFieldRaza1 = new javax.swing.JTextField();
        jTextFieldColorPelo1 = new javax.swing.JTextField();
        jTextFieldFechaNacimiento1 = new javax.swing.JTextField();
        jTextFieldVacunaciones1 = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInforme1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonModificarPeso = new javax.swing.JButton();
        jButtonModificarVacunas = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("GESTIÓN DE DATOS");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 520, 90));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 110, 30));

        jButtonVolver.setBackground(new java.awt.Color(204, 204, 255));
        jButtonVolver.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonVolver.setText("VOLVER");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 110, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Insercción de Pacientes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Vacunaciones:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        jTextFieldIdMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdMascotaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("IdMascota: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));
        getContentPane().add(jTextFieldIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 70, -1));
        getContentPane().add(jTextFieldAliasMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 70, -1));
        getContentPane().add(jTextFieldEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 70, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("AliasMascota:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, 20));
        getContentPane().add(jTextFieldRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Especie:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jTextAreaInforme.setColumns(20);
        jTextAreaInforme.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInforme);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 140, 150));

        jButtonInsertarPaciente.setText("INSERTAR PACIENTE");
        jButtonInsertarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsertarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 150, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Modificación y Eliminación de Pacientes");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 310, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Raza:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));
        getContentPane().add(jTextFieldColorPelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 70, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("ColorPelo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        jTextFieldFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 70, -1));

        jTextFieldVacunaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVacunacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldVacunaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 70, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setText("(YYYY-MM-DD)");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 90, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("FechaNacimiento:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("IdPaciente a eliminar:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));
        getContentPane().add(jTextFieldIdPaciente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 30, -1));

        jButtonEliminar.setText("ELIMINAR");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("IdMascota: ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("IdCliente:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("AliasMascota:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Especie:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Raza:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("FechaNacimiento:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 140, 60));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Vacunaciones:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));
        getContentPane().add(jTextFieldIdMascota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 70, -1));
        getContentPane().add(jTextFieldAliasMascota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 70, -1));
        getContentPane().add(jTextFieldEspecie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 70, -1));
        getContentPane().add(jTextFieldRaza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 70, -1));
        getContentPane().add(jTextFieldColorPelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 70, -1));
        getContentPane().add(jTextFieldFechaNacimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 70, -1));
        getContentPane().add(jTextFieldVacunaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 70, -1));

        jButtonModificar.setText("MODIFICAR PACIENTE");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, 20));

        jTextAreaInforme1.setColumns(20);
        jTextAreaInforme1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaInforme1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 130, 110));

        jButton1.setText("INSERTAR PESO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 150, 20));

        jButton2.setText("INSERTAR VACUNAS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, 20));

        jButtonModificarPeso.setText("MODIFICAR PESO");
        jButtonModificarPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPesoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 150, 20));

        jButtonModificarVacunas.setText("MODIFICAR VACUNAS");
        jButtonModificarVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarVacunasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarVacunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel30.setText("(YYYY-MM-DD)");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("ColorPelo:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 360, 280));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 370, 280));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/medac/tema17/practica/mascotas/interfaces/imagenes/imagen.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel1");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 780, 516));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        GestionDeDatos gestiondedatos = new GestionDeDatos();
        gestiondedatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldIdMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdMascotaActionPerformed

    private void jButtonInsertarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarPacienteActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps = null;
        boolean InserccionExitosa = false;

        int IdMascota = Integer.parseInt(jTextFieldIdMascota.getText());
        int IdCliente = Integer.parseInt(jTextFieldIdCliente.getText());
        String AliasMascota = jTextFieldAliasMascota.getText();
        String Especie = jTextFieldEspecie.getText();
        String Raza = jTextFieldRaza.getText();
        String ColorPelo = jTextFieldColorPelo.getText();
        String FechaNacimiento = jTextFieldFechaNacimiento.getText();
        int Vacunaciones = Integer.parseInt(jTextFieldVacunaciones.getText());

        ConsultasMascotasApp con1 = new ConsultasMascotasApp();

        pacientes pa1 = new pacientes(IdMascota, IdCliente, AliasMascota, Especie,
                Raza, ColorPelo, FechaNacimiento, Vacunaciones);
        String informe = pa1.toString();
        jTextAreaInforme.setText("Ha insertado lo siguiente: " + informe);

        try {

            con1.insertarMascotas(IdMascota, IdCliente, AliasMascota, Especie,
                    Raza, ColorPelo, FechaNacimiento, Vacunaciones);

            int filasActualizadas = ps.executeUpdate();

            if (filasActualizadas > 0) {
                jTextAreaInforme.setText("Ha insertado los datos correctamente. " + informe);
                InserccionExitosa = true;
            } else {
                jTextAreaInforme.setText("No se encontró al cliente con id: " + IdCliente);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InsertarYModificarPacientes.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonInsertarPacienteActionPerformed

    private void jTextFieldFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNacimientoActionPerformed

    private void jTextFieldVacunacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVacunacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVacunacionesActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps = null;
        boolean InserccionExitosa = false;

        int IdMascota = Integer.parseInt(jTextFieldIdMascota1.getText());
        String AliasMascota = jTextFieldAliasMascota1.getText();
        String Especie = jTextFieldEspecie1.getText();
        String Raza = jTextFieldRaza1.getText();
        String ColorPelo = jTextFieldColorPelo1.getText();
        String FechaNacimiento = jTextFieldFechaNacimiento1.getText();
        int Vacunaciones = Integer.parseInt(jTextFieldVacunaciones1.getText());

        ConsultasMascotasApp con1 = new ConsultasMascotasApp();

        pacientes pa1 = new pacientes(IdMascota, AliasMascota, Especie,
                Raza, ColorPelo, FechaNacimiento, Vacunaciones);
        String informe = pa1.toString();
        jTextAreaInforme1.setText("Ha modificado lo siguiente: " + informe);
        try {
            con1.modificarMascotas(IdMascota, AliasMascota, Especie,
                    Raza, ColorPelo, FechaNacimiento, Vacunaciones);

            int filasActualizadas = ps.executeUpdate();

            if (filasActualizadas > 0) {
                jTextAreaInforme1.setText("Ha insertado los datos correctamente. " + informe);
                InserccionExitosa = true;
            } else {
                jTextAreaInforme1.setText("No se encontró al cliente con id: " + IdMascota);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InsertarYModificarPacientes.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps = null;
        boolean InserccionExitosa = false;

        int IdPaciente = Integer.parseInt(jTextFieldIdPaciente2.getText());

        ConsultasMascotasApp con1 = new ConsultasMascotasApp();

        try {
            con1.eliminarMascota(IdPaciente);
            con1.eliminarPesos(IdPaciente);
            con1.eliminarVacunas(IdPaciente);
            int filasActualizadas = ps.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(InsertarYModificarPacientes.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InsertarPesos gestiondedatos = new InsertarPesos();
        gestiondedatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        InsertarVacunas gestiondedatos = new InsertarVacunas();
        gestiondedatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonModificarPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPesoActionPerformed
        // TODO add your handling code here:
        ModificarPesos gestiondedatos = new ModificarPesos();
        gestiondedatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonModificarPesoActionPerformed

    private void jButtonModificarVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarVacunasActionPerformed
        // TODO add your handling code here:
        ModificarVacunas gestiondedatos = new  ModificarVacunas();
        gestiondedatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonModificarVacunasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarYModificarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarYModificarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarYModificarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarYModificarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarYModificarPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonInsertarPaciente;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonModificarPeso;
    private javax.swing.JButton jButtonModificarVacunas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaInforme;
    private javax.swing.JTextArea jTextAreaInforme1;
    private javax.swing.JTextField jTextFieldAliasMascota;
    private javax.swing.JTextField jTextFieldAliasMascota1;
    private javax.swing.JTextField jTextFieldColorPelo;
    private javax.swing.JTextField jTextFieldColorPelo1;
    private javax.swing.JTextField jTextFieldEspecie;
    private javax.swing.JTextField jTextFieldEspecie1;
    private javax.swing.JTextField jTextFieldFechaNacimiento;
    private javax.swing.JTextField jTextFieldFechaNacimiento1;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldIdMascota;
    private javax.swing.JTextField jTextFieldIdMascota1;
    private javax.swing.JTextField jTextFieldIdPaciente2;
    private javax.swing.JTextField jTextFieldRaza;
    private javax.swing.JTextField jTextFieldRaza1;
    private javax.swing.JTextField jTextFieldVacunaciones;
    private javax.swing.JTextField jTextFieldVacunaciones1;
    // End of variables declaration//GEN-END:variables
}
