/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.tema17.practica.mascotas.interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrés
 */
public class Interfaz1 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz1
     */
    public Interfaz1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonGestionar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonListados1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Mascotas App");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 400, 120));

        jButtonGestionar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonGestionar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonGestionar.setText("GESTIONAR DATOS");
        jButtonGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 230, 50));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 90, 30));

        jButtonListados1.setBackground(new java.awt.Color(204, 204, 255));
        jButtonListados1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonListados1.setText("LISTADO DE MASCOTAS");
        jButtonListados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListados1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 270, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel1");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 706, 513));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarActionPerformed
        // TODO add your handling code here:
        
        //Abre la gestión de datos.
        GestionDeDatos gestiondedatos = new GestionDeDatos();
        gestiondedatos.setVisible(true);
        this.setVisible(false);
        
        JOptionPane.showMessageDialog(null, "Recuerda que para crear un paciente, primero necesitas crear un cliente.", "Recordatorio", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButtonGestionarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        
        //Sales de la app.
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonListados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListados1ActionPerformed
        // TODO add your handling code here:
        
        //Abres el listado.
         ListadoDeMascotas listado = new ListadoDeMascotas();
        listado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonListados1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGestionar;
    private javax.swing.JButton jButtonListados1;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
